"""Initial migration

Revision ID: 696585c17843
Revises: 
Create Date: 2025-05-16 10:16:15.013348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696585c17843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_age_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False, comment='Date of data snapshot'),
    sa.Column('label', sa.String(length=50), nullable=False, comment='Age group label (e.g. "Under 18")'),
    sa.Column('count', sa.Integer(), nullable=False, comment='Patient count for the age group'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_gender_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_location_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False, comment='Date of data snapshot'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='Location name (e.g. "Village A")'),
    sa.Column('count', sa.Integer(), nullable=False, comment='Patient count for this location'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_location_counts')
    op.drop_table('patient_gender_counts')
    op.drop_table('patient_age_categories')
    # ### end Alembic commands ###
