"""Add patient_refund_count table

Revision ID: dfd9438ef6d4
Revises: 696585c17843
Create Date: 2025-05-16 12:03:34.022825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd9438ef6d4'
down_revision = '696585c17843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_refund_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_refund_count')
    # ### end Alembic commands ###
